# .gitlab-ci.yml
#
# This GitLab CI configuration sets up a pipeline with a single test stage.
# It uses the lts Node.js Docker image and a PostgreSQL service.
#
# All jobs in this pipeline must be run manually.
#
# Environment variables are used to configure the PostgreSQL service and the ports for the account and product services.
# These variables should be set in the CI/CD settings of the GitLab project.

variables:
  POSTGRES_HOST: $POSTGRES_HOST
  POSTGRES_PORT: $POSTGRES_PORT
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_DB: $POSTGRES_TEST_DATABASE
  POSTGRES_ACCOUNT_DATABASE: $POSTGRES_TEST_DATABASE
  POSTGRES_PRODUCT_DATABASE: $POSTGRES_TEST_DATABASE
  POSTGRES_ORDER_DATABASE: $POSTGRES_TEST_DATABASE
  ACCOUNT_SERVICE_PORT: $ACCOUNT_SERVICE_PORT
  PRODUCT_SERVICE_PORT: $PRODUCT_SERVICE_PORT
  ORDER_SERVICE_PORT: $ORDER_SERVICE_PORT

image: node:lts

services:
  - postgres

stages:
  - test

AccountService-Test:
  stage: test
  script:
    - npm run install-accounts
    - npm run test-accounts
  when: manual

ProductService-Test:
  stage: test
  script:
    - npm run install-products
    - npm run test-products
  when: manual



