# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# These variables are stored in Gitlab under Settings->CI/CD->Variables
variables:
  POSTGRES_HOST: $POSTGRES_HOST
  POSTGRES_PORT: $POSTGRES_PORT
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  SHOPPER_APP_PORT: $SHOPPER_APP_PORT
  VENDOR_APP_PORT: $VENDOR_APP_PORT
  ADMIN_APP_PORT: $ADMIN_APP_PORT
  ACCOUNT_SERVICE_PORT: $ACCOUNT_SERVICE_PORT
  PRODUCT_SERVICE_PORT: $PRODUCT_SERVICE_PORT
  ORDER_SERVICE_PORT: $ORDER_SERVICE_PORT

# can make own image later
image: docker:latest

services:
  - docker:dind
  
# before_script:
#   - docker version
#   - docker-compose version

stages:          # List of stages for jobs, and their order of execution
  - test

Test:
  stage: test
  script:
    - echo "Testing"
    - apk add --update nodejs npm
    - echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
    - echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "SHOPPER_APP_PORT=$SHOPPER_APP_PORT" >> .env
    - echo "VENDOR_APP_PORT=$VENDOR_APP_PORT" >> .env
    - echo "ADMIN_APP_PORT=$ADMIN_APP_PORT" >> .env
    - echo "ACCOUNT_SERVICE_PORT=$ACCOUNT_SERVICE_PORT" >> .env
    - echo "PRODUCT_SERVICE_PORT=$PRODUCT_SERVICE_PORT" >> .env
    - echo "ORDER_SERVICE_PORT=$ORDER_SERVICE_PORT" >> .env
    - cat .env
    - ls
    - pwd
    - npm run installs
    - npm run test
    - echo "Test complete"
  when: manual

