version: "1.0"
services:
  app:
    container_name: amazon
    env_file: .env
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./AccountService/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./AccountService/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      - ./BookService/sql/schema.sql:/docker-entrypoint-initdb.d/4.schema.sql
      - ./BookService/sql/data.sql:/docker-entrypoint-initdb.d/5.data.sql