DELETE FROM product;

-- IDs are hardcoded for testing
-- single quote: ’
-- empty product
-- INSERT INTO product(data) VALUES (jsonb_build_object(
--   'name', '', 'price', 0, 'stock', 0, 'rating', 0.0, 
--   'image', ARRAY[''], 
--   'description', ARRAY[''], 
--   'category', ARRAY['']
-- ));

-- Shrek DVDs
INSERT INTO product(id, data) VALUES ('6a2212e5-af0b-4472-a724-537bdc6c571c', jsonb_build_object(
  'name', 'Shrek DVD', 'price', 19.99, 'stock', 1, 'rating', 4.8, 
  'image', ARRAY['https://m.media-amazon.com/images/I/51JSHMYGTYL._AC_UF894,1000_QL80_.jpg'], 
  'description', ARRAY['Once upon a time in a far away swamp, there lived an ornery ogre named Shrek whose precious solitude is suddenly shattered by an invasion of annoying fairy-tale characters. There are blind mice in his food, a big, bad wolf in his bed, three little homeless pigs and more, all banished from their kingdom by the evil Lord Farquaad.'], 
  'category', ARRAY['movie', 'dvd', 'shrek']
));
INSERT INTO product(id, data) VALUES ('20c6f7dd-e9c0-45a2-bef8-5f42597e4ca8', jsonb_build_object(
  'name', 'Shrek 2 DVD', 'price', 19.99, 'stock', 1, 'rating', 4.8, 
  'image', ARRAY['https://m.media-amazon.com/images/I/71HQiOZsZ6L._AC_UF1000,1000_QL80_.jpg', 'https://m.media-amazon.com/images/I/71GIXaa-bhL._SL1050_.jpg'], 
  'description', ARRAY['Lovable ogre Shrek has his marriage to a princess come under fire from her parents and a meddling fairy godmother in this sequel.'], 
  'category', ARRAY['dvd', 'movie', 'shrek']
));
INSERT INTO product(id, data) VALUES ('fb31be70-f4f3-4ccc-b483-14e831dc61d1', jsonb_build_object(
  'name', 'Shrek 3 DVD', '
  price', 19.99, 'stock', 1, 'rating', 4.7, 
  'image', ARRAY['https://m.media-amazon.com/images/I/81uE-9vcOEL._AC_UF1000,1000_QL80_.jpg', 'https://m.media-amazon.com/images/I/81g1PEZNi6L._SY445_.jpg'], 
  'description', ARRAY['Get ready for Thirds - the greatest fairytale never told continues with a while new hilarious comedy of royal proportions. When his frog-in-law suddenly croaks, Shrek embarks on another whirlwind adventure with Donkey and Puss In Boots to find the rightful heir to the throne.'], 
  'category', ARRAY['shrek', 'dvd', 'movie']
));
INSERT INTO product(id, data) VALUES ('e64edcc9-3262-49b8-bda4-066c34089e05', jsonb_build_object(
  'name', 'Shrek Forever After DVD', 'price', 19.99, 'stock', 1, 'rating', 4.8, 
  'image', ARRAY['https://m.media-amazon.com/images/I/8148AAppyOL._AC_UF894,1000_QL80_.jpg', 'https://m.media-amazon.com/images/I/81ztdNcQmZL._SL1500_.jpg'], 
  'description', ARRAY['The further adventures of the giant green ogre, Shrek, living in the land of Far, Far Away'], 
  'category', ARRAY['movie', 'dvd', 'shrek']
));

-- Macbooks
INSERT INTO product(id, data) VALUES ('fcdfc6a7-3e50-4909-818c-379f75b4320a', jsonb_build_object(
  'name', 'Apple 2022 MacBook Air Laptop with M2 chip: 13.6-inch Liquid Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera. Works with iPhone and iPad; Midnight', 'price', 849, 'stock', 200, 'rating', 4.8, 
  'image', ARRAY['https://m.media-amazon.com/images/I/719C6bJv8jL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61XufEFo1dL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61HS4BY-4rL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81jcKZq-EOL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61GAbMHjeYL._AC_SL1500_.jpg'], 
  'description', ARRAY['STRIKINGLY THIN DESIGN — The redesigned MacBook Air is more portable than ever and weighs just 2.7 pounds. It’s the incredibly capable laptop that lets you work, play or create just about anything — anywhere.', 'SUPERCHARGED BY M2 — Get more done faster with a next-generation 8-core CPU, up to 10-core GPU and up to 24GB of unified memory.', 'UP TO 18 HOURS OF BATTERY LIFE — Go all day and into the night, thanks to the power-efficient performance of the Apple M2 chip.', 'BIG, BEAUTIFUL DISPLAY — The 13.6-inch Liquid Retina display features over 500 nits of brightness, P3 wide color and support for 1 billion colors for vibrant images and incredible detail.', 'ADVANCED CAMERA AND AUDIO — Look sharp and sound great with a 1080p FaceTime HD camera, three-mic array and four-speaker sound system with Spatial Audio.', 'VERSATILE CONNECTIVITY — MacBook Air features a MagSafe charging port, two Thunderbolt ports and a headphone jack.', 'EASY TO USE — Your Mac feels familiar from the moment you turn it on, and works seamlessly with all your Apple devices.'], 
  'category', ARRAY['electronics', 'sale', 'apple']
));
INSERT INTO product(id, data) VALUES ('8e2b4bd2-e946-45c5-9796-d23baa2b0ae5', jsonb_build_object(
  'name', 'Apple 2023 MacBook Pro Laptop M3 Max chip with 16-core CPU, 40-core GPU: 16.2-inch Liquid Retina XDR Display, 48GB Unified Memory, 1TB SSD Storage. Works with iPhone/iPad; Space Black', 'price', 3699, 'stock', 4, 'rating', 4.6, 
  'image', ARRAY['https://m.media-amazon.com/images/I/618d5bS2lUL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71qArNmCH8L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71Dr4KUCjgL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71b7B8OVHvL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/718n279cEAL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61tt5IdGE3L._AC_SL1500_.jpg'], 
  'description', ARRAY['SUPERCHARGED BY M3 PRO OR M3 MAX — The Apple M3 Pro chip, with a 12-core CPU and 18-core GPU, delivers amazing performance for demanding workflows like manipulating gigapixel panoramas or compiling millions of lines of code. M3 Max, with an up to 16-core CPU and up to 40-core GPU, drives extreme performance for the most advanced workflows like rendering intricate 3D content or developing transformer models with billions of parameters.', 'UP TO 22 HOURS OF BATTERY LIFE — Go all day thanks to the power-efficient design of Apple silicon. The MacBook Pro laptop delivers the same exceptional performance whether it’s running on battery or plugged in. (Battery life varies by use and configuration. See apple.com/batteries for more information.)', 'BRILLIANT PRO DISPLAY — The 16.2-inch Liquid Retina XDR display features Extreme Dynamic Range, over 1000 nits of brightness for stunning HDR content, up to 600 nits of brightness for SDR content, and pro reference modes for doing your best work on the go. (The display has rounded corners at the top. When measured diagonally, the screen is 16.2 inches. Actual viewable area is less.)', 'FULLY COMPATIBLE — All your pro apps run lightning fast — including Adobe Creative Cloud, Apple Xcode, Microsoft 365, SideFX Houdini, MathWorks MATLAB, Medivis SurgicalAR, and many of your favorite iPhone and iPad apps. And with macOS, work and play on your Mac are even more powerful. Elevate your presence on video calls. Access information in all-new ways. And discover even more ways to personalize your Mac. (Apps are available on the App Store.)', 'ADVANCED CAMERA AND AUDIO — Look sharp and sound great with a 1080p FaceTime HD camera, a studio-quality three-mic array, and a six-speaker sound system with Spatial Audio.', 'CONNECT IT ALL — This MacBook Pro features a MagSafe charging port, three Thunderbolt 4 ports, an SDXC card slot, an HDMI port, and a headphone jack. Enjoy fast wireless connectivity with Wi-Fi 6E and Bluetooth 5.3. And you can connect up to two external displays with M3 Pro, or up to four with M3 Max. (Wi‑Fi 6E available in countries and regions where supported.)', 'MAGIC KEYBOARD WITH TOUCH ID — The backlit Magic Keyboard has a full-height function key row and Touch ID, which gives you a fast, easy, secure way to unlock your laptop and sign in to apps and sites.'], 
  'category', ARRAY['apple', 'sale', 'electronics']
));
INSERT INTO product(id, data) VALUES ('88db3140-54d2-4f1f-a552-7454bf55dcaf', jsonb_build_object(
  'name', 'Apple 2024 MacBook Air 13-inch Laptop with M3 chip: 13.6-inch Liquid Retina Display, 8GB Unified Memory, 256GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera, Touch ID; Space Gray', 'price', 999, 'stock', 100, 'rating', 4.5, 
  'image', ARRAY['https://m.media-amazon.com/images/I/71ItMeqpN3L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/617cNLYnypL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61S2t5yhVSL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71njQte16FL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/612Tf3UgLbL._AC_SL1500_.jpg'], 
  'description', ARRAY['LEAN. MEAN. M3 MACHINE — The blazing-fast MacBook Air with the M3 chip is a superportable laptop that sails through work and play.', 'PORTABLE DESIGN — Lightweight and under half an inch thin, so you can take MacBook Air anywhere you go.', 'GET MORE DONE FASTER — The powerful 8-core CPU and up to 10-core GPU of the Apple M3 chip keep things running smoothly.', 'UP TO 18 HOURS OF BATTERY LIFE — Amazing, all-day battery life so you can leave the power adapter at home.', 'A BRILLIANT DISPLAY — The 13.6-inch Liquid Retina display supports 1 billion colors.', 'LOOK SHARP, SOUND GREAT — Everything looks and sounds amazing with a 1080p FaceTime HD camera, three mics, and four speakers with Spatial Audio.', 'APPS FLY WITH APPLE SILICON — All your favorites, from Microsoft 365 to Adobe Creative Cloud, run lightning fast in macOS.'], 
  'category', ARRAY['apple', 'sale', 'electronics']
));


-- Basketballs
INSERT INTO product(id, data) VALUES ('86b0b448-fa22-4235-a88f-211e7619d44b', jsonb_build_object(
  'name', 'WILSON NCAA Street Shot Basketballs - 29.5"', 'price', 14.97, 'stock', 30, 'rating', 4.5, 
  'image', ARRAY['https://m.media-amazon.com/images/I/81w-4+yz6FL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81pmzL1XF0L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81XmaN3BpbL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81ee2sB0DpL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/8155Z80xGsL._AC_SL1500_.jpg'], 
  'description', ARRAY['OFFICIAL SIZE: This 29.5" basketball is ideal for boys age 14 and up.', 'EXTENDED DURABLITY: An interal pressure-lock bladder improves long-term durability and air rentention to keep the ball inflated.', 'ALL-COURT PERFORMANCE: A durable rubber cover makes this ball suitable for indoor and outdoor play.', 'ULTIMATE GRIP: Wilson’s signature Total Grip Technology provides enhanced softness and grip so more players can palm the ball', 'ENHANCED CONTROL: Deeper channels between the panels of the ball allow for more grip points and better ball control when dribbling and shooting.'],
  'category', ARRAY['sports', 'sale', 'basketball']
));
INSERT INTO product(id, data) VALUES ('c5f199c9-0799-43ad-848b-f7e8e76ee0e4', jsonb_build_object(
  'name', 'WILSON Evolution Indoor Game Basketballs', 'price', 79.95, 'stock', 24, 'rating', 4.8, 
  'image', ARRAY['https://m.media-amazon.com/images/I/91vdgs5FY4L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/91p-l345+FL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81joPWcgkdL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/918SMQ6MkhL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71FqoE-kMjL._AC_SL1200_.jpg'], 
  'description', ARRAY['When you focus on getting better, and not just on getting results, success takes care of itself. That is why the Wilson Evolution Game Ball is the preferred basketball in high schools across the country.', 'Signature EVO feel: the soft feel that the evolution basketball is famous for is due it’s cushion core carcass, making the ball softer to the touch and easier to grip around the rim', 'Grip & durability: the premium Evo microfiber composite cover provides a grip that players love and durability to last all-season and beyond', 'Ultimate control: laid-in composite channels create a consistent feel and texture over the entire surface of the basketball to provide unparalleled control', 'NFHS approved: approved for play by the national federation of state high school associations (NFHS)', 'Official size basketball: 29.5"', 'Proper inflation level: 7-9 psi'],
  'category', ARRAY['basketball', 'sale', 'sports']
));
INSERT INTO product(id, data) VALUES ('c85ddd6d-c3ef-4ba2-8951-a6f377c4fe94', jsonb_build_object(
  'name', 'Spalding React TF-250 Indoor-Outdoor Basketball', 'price', 41.80, 'stock', 11, 'rating', 4.5, 
  'image', ARRAY['https://m.media-amazon.com/images/I/91r8TF05ItL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/91KjvH4aX6L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/91RmCmc4mBL._AC_SL1500_.jpg'], 
  'description', ARRAY['Official size and weight: Size 7, 29.5"', 'All-surface composite leather cover', 'Butyl rubber bladder for air retention', 'Shipped inflated and game-ready', 'Designed for indoor and outdoor play'],
  'category', ARRAY['Spalding', 'basketball', 'sale', 'sports']
));
INSERT INTO product(id, data) VALUES ('443c7147-9747-4f94-bc49-4dda3b7bfc59', jsonb_build_object(
  'name', 'Molten B7G3800', 'price', 43.15, 'stock', 77, 'rating', 4.5, 
  'image', ARRAY['https://m.media-amazon.com/images/I/91v6Jz3OteL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/81sENfcL38L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/919oJhh2-QL._AC_SL1500_.jpg'], 
  'description', ARRAY['FIBA Approved', 'Official 12 panel, 2-tone design', 'Indoor/Outdoor synthetic cover', 'Butyl Bladder'],
  'category', ARRAY['Molten', 'basketball', 'sports', 'sale']
));

-- Lamps
INSERT INTO product(id, data) VALUES ('fcab207a-fd48-4e81-a15d-a754f49fcd15', jsonb_build_object(
  'name', 'PESRAE Floor Lamp, Remote Control with 4 Color Temperatures, Torchiere Floor lamp for Bedroom, Standing Lamps for Living Room, Bulb Included (Glossy Black)', 'price', 43.99, 'stock', 500, 'rating', 4.6, 
  'image', ARRAY['https://m.media-amazon.com/images/I/51zuboQ4c2L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81n+YGlN8uS._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61pAWjfWIdS._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71YUbvFOtiL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71ndCFYTunS._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/711GkYlDRhL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81QO2hB-0NL._AC_SL1500_.jpg'], 
  'description', ARRAY['9W LED dimmable remote-control bulb included; Floor lamp with 9W dimmer remote control led bulb that can be remotely controlled within 49ft', 'Stepless brightness and optional color temperature; use the remote control to adjust the brightness by stepless from 5% to 100% and color temperature from 3000k to 6000k, replaceable bulb design, which means you can choose different lights to match different scene you need', 'Multiple switching modes; This floor lamps comes with remote control and foot switch, The combination of traditional foot switch and remote control makes the tall lamps more convenient and fit for living room, bedrooms, The remote control is magnetic so you can attach it to the to a lamp or any metal surface to prevent losing it.', 'Easy to assembly; It is easy to Install, No extra tools are required, you only need to screw all the parts of the pole together to complete the assembly of this torchiere floor lamp, assembly has never been easier', 'Space-saving corner lamp; Standing lamp great for reading room and living room, the sky torchiere floor lamp easily fits beside the couch or in the corner'], 
  'category', ARRAY['lamp', 'sale', 'furniture', 'home']
));
INSERT INTO product(id, data) VALUES ('460ee6d3-e911-4b39-87f8-d342831f2b28', jsonb_build_object(
  'name', 'luckystyle Floor Lamp,Super Bright Dimmable LED Lamps for Living Room, Custom Color Temperature Standing Lamp with Remote Push Button, Adjustable Gooseneck Reading Floor Lamp for Bedroom Office Black', 'price', 33.99, 'stock', 400, 'rating', 4.6, 
  'image', ARRAY['https://m.media-amazon.com/images/I/61tKBisT-fL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71vu9HQ7WpL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61lHE0UiJ+L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61ai7mJm0oL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71dhdGHpP1L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61skUFU5uqL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71OtmralpVL._AC_SL1500_.jpg'], 
  'description', ARRAY['Upgraded Base and Lamp Head: The newly upgraded tall lamps for living room has a metal base that is heavy enough to keep it firmly placed. And it is balanced on a low pile carpet or hard floor without feeling top-heavy. With a higher quality lamp head, no flashing and blue light. Protect the eyes of you and your family. The office floor lamp are specially designed to provide bright, non-dazzling lighting.', '2 Types Control: 50ft distance remote control precisely control the LED floor reading lamps even if there are obstacles. Sensitive button control. Due to the intelligent inner build-in components of the reading light floor lamp. The magnetic remote attracts iron firmly and won’t drop. Handy to be used.', 'Versatile and Dimmable Lights: 5%-100% stepless dimmable brightness, 4 colors temperatures(3000K-6500K), you can customize your favorable lights of floor lamps for bedrooms. Click button to change the color(white, cold white, warm white, warm), craft lighting floor lamp could help you to deal with the dark, gloomy in your room.', 'Timer Setting: The living room lamp has a timing function of 30 minutes and one hour, you can set the time to turn on or off according to your needs.', 'Long Lifespan and Energy Saving: An adjustable gooseneck that allows you to rotate the flexible floor pole lamp head to any direction and angle, fixed to any position you like. The gooseneck tube is strong enough to hold it in position so it doesn’t flip or droop around when you try to adjust it. The light life of up to 100,000 hours, can reduce the cost of maintenance and replacement, completely save money and energy.'], 
  'category', ARRAY['furniture', 'sale', 'lamp', 'home']
));
INSERT INTO product(id, data) VALUES ('3f97fbe9-b883-463c-83cd-3d9e536a1d42', jsonb_build_object(
  'name', 'Standing Lamp, Led Floor Lamp with 3 Levels Dimmable Brightness, Drop-Resistant White Lampshade, Rotary Switch, Industrial Metal Floor Lamp for Living Room Bedroom Study Office Kid’s Room', 'price', 17.99, 'stock', 300, 'rating', 4.3, 
  'image', ARRAY['https://m.media-amazon.com/images/I/51sZ7VI6iTL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71ERyrroAJL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61YSjKfT1cL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/619PNJZ+5bL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71lauGialiL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71dAavusJ7L._AC_SL1500_.jpg'], 
  'description', ARRAY['Stylish Minimalist Design: This Floor lamp can easily be placed behind a sofa or next to a cabinet for easy space saving. In addition, the simple and modern design makes it not only a floor lamp for bedroom, living room, office or classroom, but also a perfect choice for home decoration. The standing lamp fits well with urban, mid-century modern, casual, or contemporary decor.', '3-Level Adjustable Brightness: This LED floor lamp features three brightness settings with a unique dimming sequence: Low-Off-Medium-Off-High-Off. This versatility makes it suitable for various activities such as reading, working, or everyday use. Each lighting mode offers gentle, eye-soothing illumination that is both functional and aesthetically pleasing.', 'E26 Bulbs Compatible: Equipped with an E26 socket, this tall lamp boasts excellent heat dissipation, ensuring a longer lifespan. It is compatible with various types of 3-level dimmable bulbs, although it is recommended to use three-way incandescent bulbs for optimal performance. (Note: 3-level dimming bulb not included, maximum 100W)', 'Safe & Easy Assembly: Simple and easy to assemble without extra tools, you just need to screw all the parts of the modern floor lamp working together by following the instruction. The bottom of the corner lamp adopts a weighted and stable design to prevent tipping and can be used near the elderly, children and pets; the lampshade is also made of resin plastic, which avoids the risk of breakage of the traditional glass lampshade.', 'Ideal Gifts for Decorative: This floor lamps for living room is a perfect holiday gift and birthday gift for mothers, fathers, wives, husbands, children, and friends. The Black Floor Lamp is also suitable for living room, bedroom, reading room, office, library, kitchen, coffee shop, hotel, restaurant, etc.'], 
  'category', ARRAY['home', 'sale', 'furniture', 'lamp']
));

-- Adidas
INSERT INTO product(id, data) VALUES ('2f804cfb-c81a-43e2-9e78-9160332e46bd', jsonb_build_object(
  'name', 'adidas Women’s Grand Court 2.0 Tennis Shoe', 'price', 59.99, 'stock', 40, 'rating', 4.6, 
  'image', ARRAY['https://a.media-amazon.com/images/I/61tF8x0bwBL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/61B4qrX2NML._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/61pngdRaLOL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/61g59QVZ+HL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/61Heb8G9-oL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/61+77WggX2L._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/81zBwlqLSUL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/71D5dbUxHfL._AC_SL1500_.jpg'], 
  'description', ARRAY['Women’s tennis sneakers with a clean look', 'LIGHTWEIGHT COMFORT: Synthetic upper for durability and light weight', 'TWO-LAYER SOCKLINER: Cloudfoam Comfort sockliner is ultra-soft and plush, with two layers of cushioning topped with soft, breathable mesh', 'RUBBER OUTSOLE: The rubber outsole provides outstanding grip and a sleek, low-profile look', 'MADE WITH RECYCLED CONTENT: Made with a series of recycled materials, this upper features at least 50% recycled content. This product represents just one of our solutions to help end plastic waste'], 
  'category', ARRAY['Women’s shoes', 'adidas', 'shoes', 'women’s clothes', 'clothing', 'women', 'shoes']
));
INSERT INTO product(id, data) VALUES ('572d681e-c916-46f2-9754-896590d82f3a', jsonb_build_object(
  'name', 'adidas Women’s Ultraboost 22 Running Shoe', 'price', 39.87, 'stock', 3, 'rating', 4.4, 
  'image', ARRAY['https://a.media-amazon.com/images/I/41QsH5MGLfL._AC_SL1000_.jpg', 'https://a.media-amazon.com/images/I/41yVmXXOfBL._AC_.jpg', 'https://a.media-amazon.com/images/I/41yVmXXOfBL._AC_.jpg', 'https://a.media-amazon.com/images/I/41emF7hRtwL._AC_.jpg', 'https://a.media-amazon.com/images/I/41BIjGe3HKL._AC_.jpg', 'https://a.media-amazon.com/images/I/41D6gL5x0BL._AC_.jpg', 'https://a.media-amazon.com/images/I/519jeZ6fSqL._AC_.jpg', 'https://a.media-amazon.com/images/I/613AEaD2LkL._AC_.jpg', 'https://a.media-amazon.com/images/I/51l9qOOF-7L._AC_.jpg'], 
  'description', ARRAY['BOOST midsole', 'Imported', 'Lace closure'], 
  'category', ARRAY['Ultraboost', 'women’s shoes', 'women’s clothes', 'adidas', 'running shoe', 'clothing', 'shoes']
));
INSERT INTO product(id, data) VALUES ('1c966d34-5079-4ead-82df-3aecc4b10d06', jsonb_build_object(
  'name', 'adidas Men’s Essentials Fleece Hoodie', 'price', 37.50, 'stock', 1000, 'rating', 4.7, 
  'image', ARRAY['https://a.media-amazon.com/images/I/71adyeaNiYL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/71ruJTxV-zL._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/61nOjtz6zDL._AC_SL1000_.jpg'], 
  'description', ARRAY['adidas mens Hooded Sweatshirt'], 
  'category', ARRAY['Hoodie', 'adidas', 'men’s fashion', 'men’s clothing', 'sale', 'clothing']
));
INSERT INTO product(id, data) VALUES ('4f9920d3-b733-4ab0-a7ef-2581a8578325', jsonb_build_object(
  'name', 'adidas Alliance Sackpack Drawstring Backpack Gym Bag, Black, One Size', 'price', 15, 'stock', 14, 'rating', 4.8, 
  'image', ARRAY['https://a.media-amazon.com/images/I/91YKb63wdfS._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/81N+kbbRLcS._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/916R20G6VTS._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/919iagHdn6S._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/91i3GpCFHVS._AC_SL1500_.jpg', 'https://a.media-amazon.com/images/I/61Gr2Fzc0lS._AC_SL1500_.jpg'], 
  'description', ARRAY['Drop mesh water bottle pockets.', 'Easy cinch opening with durable cording straps.', 'Zippered exterior pocket for your phone or small stuff.'], 
  'category', ARRAY['Gym Drawstring Bags by Adidas', 'adidas', 'bags', 'drawstring bags', 'sports']
));
INSERT INTO product(id, data) VALUES ('91341777-8bfc-4dcf-97a8-29c6542c744e', jsonb_build_object(
  'name', 'adidas Unisex-Adult Adissage Slides Sandal', 'price', 20, 'stock', 100, 'rating', 4.4, 
  'image', ARRAY['https://m.media-amazon.com/images/I/41QXpdDWq-L._AC_SL1000_.jpg', 'https://m.media-amazon.com/images/I/41TBMZ+z8oL._AC_.jpg', 'https://m.media-amazon.com/images/I/31uCcQwUeeL._AC_.jpg', 'https://m.media-amazon.com/images/I/31zTdnN1KJL._AC_.jpg', 'https://m.media-amazon.com/images/I/31-3HRbtQpL._AC_.jpg', 'https://m.media-amazon.com/images/I/41IodvHk7PL._AC_.jpg', 'https://m.media-amazon.com/images/I/51-WjUCSFjL._AC_.jpg', 'https://m.media-amazon.com/images/I/61p4C1dZ4UL._AC_.jpg'], 
  'description', ARRAY['Adjustable fit; Hook-and-loop closure', 'Single-bandage EVA upper for lightweight comfort', 'EVA massage nubs on footbed', 'Cloudfoam midsole and memory foam sockliner for step-in comfort and superior cushioning'], 
  'category', ARRAY['Sandals', 'adidas', 'sports', 'clothing', 'shoes', 'unisex']
));
  
-- Smartphones
INSERT INTO product(id, data) VALUES ('d9b42b3d-aa46-4791-8470-c9417d1db025', jsonb_build_object(
  'name', 'SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Cobalt Violet', 
  'price', 784.99, 'stock', 123, 'rating', 4.4, 
  'image', ARRAY['https://m.media-amazon.com/images/I/716UvwH-NvL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/715STRtiLbL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/711ru1TUtXL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81SAEi78GkL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71klvX4OIjL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71s3o-fls4L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61h4ZPaIdkL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71AFQz2LlmL._AC_SL1500_.jpg'], 
  'description', ARRAY['CIRCLE & SEARCH¹ IN A SNAP: What’s your favorite influencer wearing? Where’d they go on vacation? What’s that word mean? Don’t try to describe it — use Circle to Search1 with Google to get the answer; With S24 Series, circle it on your screen and learn more', 'REAL EASY, REAL-TIME TRANSLATIONS: Speak foreign languages on the spot with Live Translate²; Unlock the power of convenient communication with near real-time voice translations, right through your Samsung Phone app', 'NOTE SMARTER, NOT HARDER: Focus on capturing your notes and spend less time perfecting them; Note Assist³ will summarize, format, and even translate them for you; All of your notes are organized neatly so that you can find what you need', 'MORE WOW, LESS WORK: Turn every photo into a post-worthy masterpiece; Move or remove objects; Fill in empty space; Simply snap a pic and take it from great to jaw-dropping with Generative Edit', 'CAPTURE. SHARE. IMPRESS: Share more of life’s most share-worthy moments in natural, true-to-life color with 50MP camera', 'OUR MOST POWERFUL GALAXY SMARTPHONE YET: Jump seamlessly between apps without the wait and see content in high quality with our fastest processor yet, Snapdragon 8 Gen 3 for Galaxy⁵', 'PUT YOUR BEST TEXT FORWARD: Say the right thing at the right time in no time with Chat Assist⁶; Get real-time tone suggestions to make your writing sound more professional or conversational; Plus, make typos a thing of the past'], 
  'category', ARRAY['Cell Phones by SAMSUNG', 'samsung', 'cell phone', 'smartphones', 'electronics', 'sale']
));
INSERT INTO product(id, data) VALUES ('721d0dfe-c061-4737-a757-a440eac199c2', jsonb_build_object(
  'name', 'OnePlus 12,16GB RAM+512GB,Dual-SIM,Unlocked Android Smartphone,Supports 50W Wireless Charging,Latest Mobile Processor,Advanced Hasselblad Camera,5400 mAh Battery,2024,Flowy Emerald', 
  'price', 899.99, 'stock', 867, 'rating', 4.6, 
  'image', ARRAY['https://m.media-amazon.com/images/I/711F6T6aySL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81RZHSigxQL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61Sru-13o8L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61TsuQvqJ5L._AC_SL1500_.jpg'], 
  'description', ARRAY['Free 6 months of Google One and 3 months of Youtube Premium with purchase of OnePlus 12. (New accounts only for each service to qualify)', 'Pure Performance: The OnePlus 12 is powered by the latest Snapdragon 8 Gen 3, with up to 16GB of RAM. The improved processing power & graphics performance is supported by the latest Dual Cryo-velocity VC cooling chamber, which improves thermal efficiency & heat dissipation.', 'Brilliant Display: The OnePlus 12 has a stunning 2k 120Hz Super Fluid Display, with advanced LTPO for a brighter, smoother, and more vibrant viewing experience. With 4500 nits peak brightness, enjoying your content is effortless anywhere.', 'Powered by Trinity Engine: The OnePlus 12’s performance is optimized by the Trinity Engine, which accelerates various softwares to maximize the performance of your device. These include RAM-Vita, CPU-Vita, ROM-Vita, HyperTouch, HyperBoost, and HyperRendering (visit the official product page for more information).', 'Powerful, Versatile Camera: Explore the new 4th Gen Hasselblad Camera System for Mobile, packed with computational photography software and improved sensors. The OnePlus 12 boasts a 50MP primary camera, a 64MP 3x Periscope Lens, and a 48MP Ultra-Wide Camera, all packed together with industry-leading Hasselblad color science.', 'Ultra Fast Charging: A massive 5400 mAh battery is powered by an 80W SUPERVOOC Charger, plus the OnePlus 12 can charge wirelessly at 50W using a proprietary OnePlus 50W AIRVOOC Charger.'], 
  'category', ARRAY['Cell Phones by OnePlus', 'oneplus', 'cell phone', 'smartphones', 'electronics']
));
INSERT INTO product(id, data) VALUES ('5c696138-322c-41ec-9383-396f563ffe93', jsonb_build_object(
  'name', 'REDMAGIC 9 Pro Smartphone 5G, 120Hz Gaming Phone, 6.8" Full Screen, Under Display Camera, 6500mAh Android Phone, Snapdragon 8 Gen 3, 12+256GB, 80W Charger, Dual-Sim, US Unlocked Cell Phone Black', 
  'price', 749, 'stock', 456, 'rating', 4.3, 
  'image', ARRAY['https://m.media-amazon.com/images/I/51eUDrkf9RL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71tbSQK9jPL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61q4XnyvOYL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61tvqjBXp+L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/615uFTw75OL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/616puSVs2sL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71bVM4sDbEL._AC_SL1500_.jpg'], 
  'description', ARRAY['【6.8" FHD+ Full Screen】Gaming Phone with a 120Hz refresh rate and a resolution of 2480 x 1116 pixels, this 6.8" FHD+ Full AMOLED screen delivers beautiful HD+ visuals at up to 120 frames per second. With a 960Hz touch sampling rate for multi fingers, the Cell Phone delivers ultra-fast touch and precise response, giving you a serious competitive edge while gaming. The 5G Smartphone have also Under-display Fingerprint Sensor and 16MP Under Display Camera.', '【Latest Chip and Larger Storage】The Gaming Smartphone has the latest Qualcomm Snapdragon 8 Gen 3 (Red Core 2 Pro + UFS 4.0 + LPDDR5X). Play your favorite games with ease with the raw power of the new CPU clocking in at nearly 3.2GHz and enjoy Triple-A graphics thanks to the fast rendering power of the GPU. 12GB RAM + 256GB ROM provides not only a fun gaming experience and effects, also large storage space for game downloads.', '【Multi-Dimensional Cooling System】The Gaming Phone incorporates new aerospace-grade phase change materials (PCM) . Heat can be stored inside this material and released slowly so you feel less heat from the phone while playing, making it more comfortable to hold the phone. The High-Speed Built-In Turbofan accelerates heat dissipation and the fan noise is as quiet as a whisper.', '【5G & WIFI Connection and 6500mAh Battery】5G is SA+NSA dual mode and supports all key regions up to 3.0 Gbps uploads, up to 7.5 Gbps downloads. WIFI 7 is up to 3.5Gbps. These bring mobile gaming to a whole new level. Download the latest games and videos in gigabit speeds with ease to show off your smooth, low latency experience. The Cell Phone certified 80W GAN charger and supports 80W fast charging.', '【Ultra HD AI Quad Camera】Rear Camera are Samsung GN5 50MP(Wide) + Samsung JN1 50MP(Ultrawide) + 2MP(Macro). The primary camera is upgraded to enable users to take fantastic photos and videos with a fast auto focus, even in the dimmest scenario. Every detail is captured. Thanks to dual pixel focusing, it ensures fast autofocus regardless. Front Camera is 16 Megapixel and 5nd generation under-display-camera.'], 
  'category', ARRAY['Cell Phones by REDMAGIC', 'redmagic', 'cell phone', 'smartphones', 'electronics', 'gaming']
));
INSERT INTO product(id, data) VALUES ('dffb74f2-060c-4b4f-b838-92e49394fcea', jsonb_build_object(
  'name', 'Google Pixel 8 - Unlocked Android Smartphone with Advanced Pixel Camera, 24-Hour Battery, and Powerful Security - Hazel - 256 GB', 
  'price', 609, 'stock', 56, 'rating', 4.3, 
  'image', ARRAY['https://m.media-amazon.com/images/I/71SfoZu9a3L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81kir2fBpJL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81HzhKILmkL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81cRIHRkzCL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/816oWLrLIEL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71lfbifwR5L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81eKg-3vWEL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71alRFofbEL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81HBNeCkItL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81uiS4T2wdL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71AQpqXQ5ML._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71Zb0QByDhL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71DGX4nnjnL._AC_SL1500_.jpg'], 
  'description', ARRAY['Pixel 8 is the helpful phone engineered by Google; the new Google Tensor G3 chip is custom-designed with Google AI for cutting-edge photo and video features and smarter ways to help', 'Unlocked Android 5G phone gives you the flexibility to change carriers and choose your own data plan; it works with Google Fi, Verizon, T-Mobile, AT&T, and other major carriers', 'Google Pixel 8 has a fully upgraded camera with advanced image processing to reveal vivid colors and striking details; and now with Macro Focus, even the smallest subjects can become spectacular images', 'The 6.2-inch Pixel 8 Actua display is super sharp, with rich, vivid colors; it’s fast and responsive for smoother gaming, scrolling, and moving between apps', 'Pixel’s Adaptive Battery can last over 24 hours; when Extreme Battery Saver is turned on, it can last up to 72 hours; and it charges faster than ever', 'Pixel 8 can notify first responders in an emergency and share your location, and can even detect if you’ve been in a severe car crash; if you’re unable to respond, your Pixel phone can call emergency services and notify your chosen contacts', 'With powerful security features, your Pixel phone helps keep your info safe; Google Tensor G3, VPN by Google One, and the Titan M2 security chip give your Pixel multiple layers of security'], 
  'category', ARRAY['Cell Phones by Google', 'google', 'cell phone', 'smartphones', 'electronics', 'sale']
));
INSERT INTO product(id, data) VALUES ('cf5bb11d-ad94-4401-8d00-08377079bc29', jsonb_build_object(
  'name', 'Honor Magic5 Pro 5G 512GB ROM 12GB RAM Smartphone 6.81" 120Hz 50MP AI Triple Camera, Dual SIM, Mobile Cell Phone Global EU/UK Model PGT-N19 Mobile Cell Phone (Green)', 
  'price', 999, 'stock', 6, 'rating', 4.6, 
  'image', ARRAY['https://m.media-amazon.com/images/I/71e92vj7YcL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71j6dGhJqCL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/7185t7uCBOL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71WorAZg0yL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/711-0qnBcCL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71x4CYLYjfL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81UXyceT8TL._AC_SL1500_.jpg'], 
  'description', ARRAY['【AI Motion Detection Capture】 HONOR Magic5 Pro can detect motion and capture the best shot automatically. Millisecond motion detection capture lets you easily take a photo, day or night, from far or near.', '【Super Dynamic Vivid Screen】 With the no. Ranked #1 in the DXOMARK Smartphone Display Ranking, the HONOR Magic5 Pro features a 6.81" LTPO Quad-Curved Floating Display 120Hz with 2160Hz PWM Dimming, ensuring an immersive and comfortable viewing experience.', '【Battery Innovation】HONOR Magic5 Pro uses a 5100mAh battery that offers 12.8% higher energy density compared to lithium batteries for longer use. Support up to 17 hours of online YouTube video playback or 11 hours of Snapchat browsing.', '【Best Wireless Transmission】HONOR Magic5 Pro features the industry’s first Wi-Fi/Bluetooth independent antenna architecture, which prevents interference between the two wireless networks, allows data to be transferred simultaneously, and allows you to stay connected even in a basement or in an elevator.', '【Flagship Performance】HONOR Magic5 Pro features the latest Snapdragon 8 Gen 2 mobile platform, an advanced 4nm processor with integrated Qualcomm Kryo CPU and Qualcomm Adreno GPU, enabling seamless productivity and uninterrupted entertainment at any time.'], 
  'category', ARRAY['Cell Phones by Honor', 'honor', 'huawei', 'cell phone', 'smartphones', 'electronics']
));
