services:
  app:
    container_name: app
    env_file: .env
    image: app:latest
    depends_on:
      - postgres
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '3014:3014'


  postgres:
    container_name: pginstance
    image: postgres:alpine
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./AccountService/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./AccountService/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      - ./OrderService/sql/schema.sql:/docker-entrypoint-initdb.d/4.schema.sql
      - ./OrderService/sql/data.sql:/docker-entrypoint-initdb.d/5.data.sql
      - ./ProductService/sql/schema.sql:/docker-entrypoint-initdb.d/6.schema.sql
      - ./ProductService/sql/data.sql:/docker-entrypoint-initdb.d/7.data.sql
