----- DO NOT CHANGE ANYTHING IN THIS FILE ------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE DATABASE accountdatabase;

CREATE DATABASE productdatabase;

CREATE DATABASE orderdatabase;

----- DO NOT CHANGE ANYTHING IN THIS FILE ------